Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
step_sizes = [0.2, 0.1, 0.05, 0.025, 0.02, 0.0125, 0.01, 0.005]

num_pts = np.zeros(len(step_sizes))
times = np.zeros_like(num_pts)
for idx, step_size in enumerate(step_sizes):
    num_pts[idx], times[idx] = heat_equation(step_size)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mMemoryError[0m                               Traceback (most recent call last)
Cell [0;32mIn[10], line 6[0m
[1;32m      4[0m times [38;5;241m=[39m np[38;5;241m.[39mzeros_like(num_pts)
[1;32m      5[0m [38;5;28;01mfor[39;00m idx, step_size [38;5;129;01min[39;00m [38;5;28menumerate[39m(step_sizes):
[0;32m----> 6[0m     num_pts[idx], times[idx] [38;5;241m=[39m [43mheat_equation[49m[43m([49m[43mstep_size[49m[43m)[49m

Cell [0;32mIn[9], line 17[0m, in [0;36mheat_equation[0;34m(h)[0m
[1;32m     12[0m num_pts [38;5;241m=[39m [38;5;28mlen[39m(x_vals)[38;5;241m*[39m[38;5;28mlen[39m(y_vals)
[1;32m     14[0m [38;5;66;03m# The coefficient matrix A is now m*n by m*n, [39;00m
[1;32m     15[0m [38;5;66;03m# since that is the total number of points.[39;00m
[1;32m     16[0m [38;5;66;03m# The right-hand side vector b is m*n by 1.[39;00m
[0;32m---> 17[0m A [38;5;241m=[39m [43mnp[49m[38;5;241;43m.[39;49m[43mzeros[49m[43m([49m[43m([49m[43mnum_pts[49m[43m,[49m[43m [49m[43mnum_pts[49m[43m)[49m[43m)[49m
[1;32m     18[0m b [38;5;241m=[39m np[38;5;241m.[39mzeros(num_pts)
[1;32m     20[0m u_left [38;5;241m=[39m [38;5;241m100[39m

[0;31mMemoryError[0m: Unable to allocate 12.2 GiB for an array with shape (40401, 40401) and data type float64
MemoryError: Unable to allocate 12.2 GiB for an array with shape (40401, 40401) and data type float64

